name: 'fish_shop'
version: '1.0.0'

profile: 'fish_shop'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  fish_shop:
    raw:
      materialized: table
      +schema: ale_pipeline_raw
      +tags:
        - raw
        - sales
    entity:
      materialized: table
      +schema: ale_pipeline_entity
      +tags:
        - entity
        - sales
    pivot:
      materialized: table
      +schema: ale_pipeline_pivot
      +tags:
        - pivot
        - sales
