fish_shop:
  outputs:
    dev:
      dataset: ale_dataset
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: ./keyfile.json
      location: US
      method: service-account
      priority: interactive
      project: savvy-range-365915
      threads: 1
      type: bigquery
  target: dev
